# Generated by Django 4.1.1 on 2022-09-27 14:45

import blogs.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_postsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsimage',
            name='image',
            field=models.ImageField(upload_to='posts/images', validators=[blogs.validators.validate_file_size]),
        ),
        migrations.CreateModel(
            name='BloggersImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bloggers/images', validators=[blogs.validators.validate_file_size])),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blogs.blogger')),
            ],
        ),
    ]
